import XCTest

/// Launch helpers and shared XCUIApplication wiring for the e2e suite.
///
/// All tests in this target talk to the *real* `Harness.app` produced by
/// `scripts/package.sh` — the same bundle a user would double-click. The
/// only departure from production is `HARNESS_FAKE_PROVIDER=1`, which
/// swaps the Anthropic adapter for a deterministic in-process fake (see
/// `backend/crates/harness-server/src/testing.rs`). Everything else —
/// SQLite, sidecar handshake, SSE streaming, sandbox-exec — runs unchanged.
///
/// Each test owns its own SQLite by writing to a fresh tempdir, so runs
/// don't bleed state into each other and the suite is safe to run in
/// parallel on CI.
enum HarnessAppLaunch {
    /// The bundle under test. Resolution order:
    ///   1. `HARNESS_TEST_APP_PATH` env var (CI sets this explicitly).
    ///   2. `dist/Harness.app` relative to the source root, walked up
    ///      from the bundle that contains this xctest.
    ///   3. Fail with a descriptive message naming `make app`.
    ///
    /// The scheme generated by xcodegen runs `xcodebuild test` after
    /// building both the app and the UITest bundle, so the .app sits at
    /// `<DerivedData>/Build/Products/<Configuration>/Harness.app`. We
    /// honour that first via `xcodebuild`'s `BUILT_PRODUCTS_DIR`, then
    /// fall back to the dist path so a developer can iterate locally.
    static func resolveAppPath() throws -> String {
        let env = ProcessInfo.processInfo.environment
        if let explicit = env["HARNESS_TEST_APP_PATH"], !explicit.isEmpty {
            return explicit
        }
        if let built = env["BUILT_PRODUCTS_DIR"] {
            let candidate = (built as NSString).appendingPathComponent("Harness.app")
            if FileManager.default.fileExists(atPath: candidate) {
                return candidate
            }
        }
        // Walk from the test bundle up to the repo root, then into dist/.
        var dir = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // HarnessUITests/
            .deletingLastPathComponent() // UITests/
            .deletingLastPathComponent() // macos/
            .deletingLastPathComponent() // <repo>
        // Climb at most a few levels in case the source layout changes.
        for _ in 0..<4 {
            let candidate = dir.appendingPathComponent("dist/Harness.app").path
            if FileManager.default.fileExists(atPath: candidate) {
                return candidate
            }
            dir = dir.deletingLastPathComponent()
        }
        throw XCTSkip("""
            Harness.app not found. Build it with `make app` (or set \
            HARNESS_TEST_APP_PATH explicitly) before running the UI tests.
            """)
    }

    /// Build a per-test temp DB path. Cleaned up by the launch helper's
    /// teardown; never reused across tests.
    static func makeTempDBPath() -> String {
        let tmpDir = NSTemporaryDirectory()
        let name = "harness-uitest-\(UUID().uuidString).sqlite"
        return (tmpDir as NSString).appendingPathComponent(name)
    }

    /// Fixed 32-byte (hex-encoded) test key. The fake provider doesn't
    /// touch real data, so the key is stable across runs without being
    /// security-sensitive.
    static let testDBKeyHex =
        "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff"
}

/// Convenience XCTestCase base that:
///   * resolves the .app once per test class,
///   * launches a fresh XCUIApplication per test method with the fake
///     provider env wired up,
///   * waits for the chat root to render before yielding control to the
///     test body.
///
/// Subclass this and override `setUp()`/`tearDown()` only if you need to
/// drive a different launch profile.
class HarnessE2ETestCase: XCTestCase {
    var app: XCUIApplication!
    var tempDBPath: String!

    /// Subclasses can override to inject extra env (e.g. delays, failure
    /// modes). Defaults to the headline e2e profile.
    func extraLaunchEnvironment() -> [String: String] { [:] }

    override func setUpWithError() throws {
        try super.setUpWithError()
        continueAfterFailure = false

        let appPath = try HarnessAppLaunch.resolveAppPath()
        tempDBPath = HarnessAppLaunch.makeTempDBPath()

        app = XCUIApplication(url: URL(fileURLWithPath: appPath))
        var env: [String: String] = [
            // Sidecar discovery — explicit so the launcher doesn't go
            // hunting through Bundle.main lookups inside the test runner.
            "HARNESS_BACKEND_PATH":
                (appPath as NSString).appendingPathComponent("Contents/MacOS/harness-server"),
            "HARNESS_FAKE_PROVIDER": "1",
            // Per-test SQLite so runs are isolated. The directory exists
            // (NSTemporaryDirectory always does); the file is created by
            // sqlx when the backend boots.
            "HARNESS_DB_PATH": tempDBPath,
            "HARNESS_DB_KEY_HEX": HarnessAppLaunch.testDBKeyHex,
        ]
        for (k, v) in extraLaunchEnvironment() {
            env[k] = v
        }
        app.launchEnvironment = env

        app.launch()
        try waitForChatRoot()
    }

    override func tearDownWithError() throws {
        // Quit the app cleanly so the sidecar gets SIGTERM, then drop the
        // temp DB so we don't leak state between tests.
        if let app, app.state == .runningForeground {
            app.terminate()
        }
        if let path = tempDBPath {
            try? FileManager.default.removeItem(atPath: path)
        }
        try super.tearDownWithError()
    }

    /// The chat root is the post-bootstrap state: the sidebar exists and
    /// the loading view is gone. We use the sidebar's "+ New Conversation"
    /// button as the witness because it's always present once the
    /// backend handshake completes, irrespective of how many conversations
    /// are persisted.
    func waitForChatRoot(timeout: TimeInterval = 15) throws {
        let newButton = app.buttons["New Conversation"]
        if !newButton.waitForExistence(timeout: timeout) {
            // Surface the "Backend failed to start" diagnostic if it's
            // visible, so a CI failure makes the cause obvious.
            let failure = app.staticTexts["Backend failed to start"]
            if failure.exists {
                XCTFail("backend bootstrap failed: \(failure.label)")
                return
            }
            XCTFail("chat root did not appear within \(timeout)s — sidebar 'New Conversation' button not found")
        }
    }

    // MARK: - High-level interactions

    /// Open the new-conversation sheet via Cmd-N, fill it, click Create.
    /// `providerDisplay`/`modelDisplay` are matched against the picker's
    /// rendered labels (e.g. "Fake Claude").
    func createConversation(
        providerDisplay: String = "Fake Claude",
        modelDisplay: String = "Fake Claude",
        title: String? = nil,
        sandboxName: String? = nil
    ) throws {
        // Cmd-N opens the sheet. The keyboardShortcut("n", .command) on
        // the sidebar's "+" button binds this globally for the window.
        app.typeKey("n", modifierFlags: .command)

        let sheet = app.sheets.firstMatch
        XCTAssertTrue(sheet.waitForExistence(timeout: 5), "new-conversation sheet did not appear")

        // The pickers render as XCUIElement.ElementType.popUpButton on
        // macOS. We select by visible label rather than tag.
        try selectPopUp(in: sheet, label: "Provider", value: providerDisplay)
        try selectPopUp(in: sheet, label: "Model", value: modelDisplay)
        if let sandboxName {
            try selectPopUp(in: sheet, label: "Sandbox", value: sandboxName)
        }

        if let title {
            let titleField = sheet.textFields["Title (optional)"]
            XCTAssertTrue(titleField.waitForExistence(timeout: 2))
            titleField.click()
            titleField.typeText(title)
        }

        let create = sheet.buttons["Create"]
        XCTAssertTrue(create.isEnabled, "Create button is disabled — provider/model not selected?")
        create.click()
    }

    /// Type a message into the composer and send it via ⌘↩.
    func sendMessage(_ text: String) {
        let composer = app.textFields["Message"]
        XCTAssertTrue(composer.waitForExistence(timeout: 5), "composer text field not found")
        composer.click()
        composer.typeText(text)
        // ⌘↩ — Composer.swift binds Send to .return + .command.
        app.typeKey(.return, modifierFlags: .command)
    }

    /// Wait for a message bubble whose visible text contains `substring`.
    /// Returns true on match; false on timeout.
    @discardableResult
    func waitForAssistantText(containing substring: String, timeout: TimeInterval = 5) -> Bool {
        // Message bubbles render their text via SwiftUI Text views, which
        // surface to AX as staticText elements. We match on label CONTAINS
        // because streamed text may grow incrementally.
        let predicate = NSPredicate(format: "label CONTAINS[c] %@", substring)
        let match = app.staticTexts.matching(predicate).firstMatch
        return match.waitForExistence(timeout: timeout)
    }

    /// Wait for the inline error banner to render with the given fragment.
    @discardableResult
    func waitForErrorBanner(containing substring: String, timeout: TimeInterval = 5) -> Bool {
        let predicate = NSPredicate(format: "label CONTAINS[c] %@", substring)
        return app.staticTexts.matching(predicate).firstMatch.waitForExistence(timeout: timeout)
    }

    // MARK: - Helpers

    private func selectPopUp(in scope: XCUIElement, label: String, value: String) throws {
        let popUp = scope.popUpButtons[label]
        XCTAssertTrue(popUp.waitForExistence(timeout: 2), "picker '\(label)' not found")
        popUp.click()
        let menuItem = app.menuItems[value]
        XCTAssertTrue(menuItem.waitForExistence(timeout: 2), "menu item '\(value)' not found in picker '\(label)'")
        menuItem.click()
    }
}
